### ISSUE TITLE
drag and drop optimized version

### ISSUE THREAD

**Issue by max-mapper** [karissa/dat-app#6]
heres a rough mockup

<img width="565" alt="screen shot 2016-02-25 at 8 12 15 pm" src="https://cloud.githubusercontent.com/assets/39759/13342979/2059326c-dbfc-11e5-9805-c5bef76aeb66.png">

**Comment by max-mapper** [comment]
if you drop a folder, it makes sense to me to show the folder name like it shows up above. but if you drop one file, should it show this?

<img width="290" alt="screen shot 2016-02-25 at 8 14 33 pm" src="https://cloud.githubusercontent.com/assets/39759/13343004/6964df06-dbfc-11e5-8bf9-3e04da153877.png">

**Comment by max-mapper** [comment]
after talking more, how about this instead

<img width="227" alt="screen shot 2016-02-25 at 9 47 57 pm" src="https://cloud.githubusercontent.com/assets/39759/13344281/7717a964-dc09-11e5-8f83-1c52fa21da25.png">

**Comment by okdistribute** [comment]
i like the icons!
